<a href="https://colab.research.google.com/github/snghynn/ESAA-YB/blob/main/ESSA_0310_HW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter1. 파이썬 기반의 머신러닝과 생태계 이해

## 1. 머신러닝의 개념

- 머신러닝: 애플리케이션을 수정하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법

- 머신러닝의 분류

  1) 지도학습: 분류, 회귀, 추천 시스템, 시각/음성감지/인지/텍스트 분석/NLP

  2) 비지도학습: 클러스터링, 차원 축소, 강화 학습

## 2. 파이썬 머신러닝 생태계를 구성하는 주요 패키지

## 3. 넘파이
- 넘파이: 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지/ 배열 기반의 연산과 다양한 데이터 핸들링 기능 제공
- 넘파이 array()함수는 파이썬의 리스트와 같은 다양한 인자를 입력받아 ndarray로 변환하는 기능을 수행
- 생성된 ndarray 배열의 shape 변수는 ndarray의 크기(행과 열의 수)를 튜플 형태로 가져 ndarray 배열의 차원까지 알 수 있음

In [2]:
import numpy as np

In [3]:
array1=np.array([1,2,3])
print('array1 type: ',type(array1))
print('array1 array 형태: ', array1.shape)

array2=np.array([[1,2,3],
                 [2,3,4]])
print('array2 type: ',type(array2))
print('array2 array 형태: ', array2.shape)

array3=np.array([[1,2,3]])
print('array3 type: ',type(array3))
print('array3 array 형태: ', array3.shape)


array1 type:  <class 'numpy.ndarray'>
array1 array 형태:  (3,)
array2 type:  <class 'numpy.ndarray'>
array2 array 형태:  (2, 3)
array3 type:  <class 'numpy.ndarray'>
array3 array 형태:  (1, 3)


### np.array() 사용법

- ndarray로 변환을 원하는 객체를 인자로 입력하면 ndarray를 반환.

- ndarray.shape는 ndarray의 차원과 크기를 튜플 형태로 나타내줌


In [4]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


### ndarray의 데이터 타입

- 숫자, 문자열, 불 값 모두 가능

- int형(8bit, 16bit, 32bit), unsigned int형(8bit, 16bit, 32bit), float형(16bit, 32bit, 64bit, 128bit), complex타입

- 한 개의 ndarray 객체에는 같은 type만 가능

- ndarray 내의 데이터 타입은 dtype 속성으로 확인 가능


In [5]:
list1=[1,2,3]   #리스트 자료형, integer을 값으로 가짐
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


- list -> 서로 다른 데이터 타입 가능
- ndarray -> 같은 데이터 타입만 가능
- list -> ndarray 로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환 일괄 적용

In [6]:
list2=[1,2,'test'] #int형 값과 문자열이 섞여있는 리스트트
array2=np.array(list2) #list형 자료를 ndarray로 변경하기
print(array2, array2.dtype) 
#int형이 문자열 값으로 변환됨

['1' '2' 'test'] <U21


In [7]:
list3=[1,2,3.0] #int와 float형이 섞여 있음
array3=np.array(list3) #array로 변경
print(array3, array3.dtype)
#int형이 float형으로 변환됨

[1. 2. 3.] float64


- astype() : ndarray 내 데이터값의 타입 변경
- 인자로 원하는 타입을 문자열로 지정
- 데용량 데이터의 메모리 절약을 위해 사용

In [8]:
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float, array_float.dtype)

[1. 2. 3.] float64


In [9]:
array_int1=array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1 2 3] int32


In [10]:
array_float1=np.array([1.1, 2.1, 3.1])
array_int2=array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1 2 3] int32


### ndarray를 편리하게 생성하기-arange, zeros, ones

- arange(), zeros(), ones(): 특정 크기와 차원을 가진 ndarray를 연속값이나 0또는 1로 초기화해 쉽게 생성해야 하는 경우 사용
- 테스트용 데이터 만들거나 대규모의 데이터 일괄적으로 초기화해야할 때 

In [11]:
sequence_array=np.arange(10)  #range()와 유사한 기능
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [12]:
#zeros(): 모든 값을 0으로 채운 해당 shpae를 가진 ndarray 반환
zero_array=np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [13]:
#ones(): 모든 값을 1로 채운 해당 shape를 가진 ndarray 반환
#dtype 지정하지 않으면 default로 float64형의 데이터로 채움
one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### ndarray의 차원과 크기를 변경하는 reshape()

- reshape(): array를 특정 차원 및 크기로 변환
- 변환을 원하는 크기를 함수 인자로 부여여

In [14]:
#0~9까지의 1차원 ndarray를 2row*5col(array2)과 5row*2col(array3) 형태로 2차원 ndarray로 변환

array1=np.arange(10)
print('array:\n', array1)

array2=array1.reshape(2,5)
print('array2:\n',array2)

array3=array1.reshape(5,2)
print('array3:\n',array3)

array:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [15]:
array1.reshape(4,3) #지정된 사이즈로 변경이 불가능할 경우 오류

ValueError: ignored

In [19]:
#reshape()에서 -1을 인자로 적용할 경우, 원래 ndarray와 호환되는 새로운 shpae로 변환해줌

array1=np.arange(10)
print(array1)
array2=array1.reshape(-1,5)
print('array2:\n',array2)
print('array2 shape:', array2.shape)
array3=array1.reshape(5,-1)
print('array3:\n', array3)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array2 shape: (2, 5)
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array3 shape: (5, 2)


In [20]:
array4=array1.reshape(-1,4) #4가 10의 약수가 아니므로 -1을 사용하더라도 호환될 수 없는 형태

ValueError: ignored

In [21]:
#reshape(-1,1)을 이용해 2차원 ndarray로 변환하기
array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5=array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6=array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(indexing)

1. 특정한 데이터만 추출: 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 변환
2. 슬라이싱(Slicing): 슬라이싱은 연속된 인덱스상의 ndarray를 추출하는 방식 ':'기호 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스-1 위치에 있는 데이터의 ndarray를 반환함
3. 팬시 인덱싱(Fancy indexing): 일정한 인덱싱 집합을 리스트 또는 ndarray형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환
4. 불린 인덱싱(Boolean indexing): 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환


### 단일 값 추출

In [22]:
#1부터 9까지의 1차원 ndarray 생성
array1=np.arange(start=1, stop=10)
print('array1:',array1)

#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value=array1[2]
print('value: ', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value:  3
<class 'numpy.int64'>


In [23]:
#단일 인덱스 이용해 ndarray 내의 데이터값 수정하기
array1[0]=9
array1[8]=0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [25]:
#다차원 ndarray에서 단일값 추출
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])
# [row=0, col=1] == [axis0=0, axis1=1]
# axis0 = row, axis1 = col 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


### 슬라이싱

- ':' 기호를 이용해 연속한 데이터를 슬라이싱해서 추출
- 단일 데이터값 추출을 제외하고 슬라이싱, 팬시 인덱싱, 불린 인덱싱으로 추출된 데이터 세트는 모두 ndarray 타입

In [26]:
array1= np.arange(start=1, stop=10)
array3= array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


- ':' 사이의 시작, 종료 인덱스는 생략 가능
1. 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주
2. 종료 인덱스 생략 경우 자동으로 맨 마지막 인덱스로 간주
3. 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주

In [27]:
array1=np.arange(start=1, stop=10)
print(array1)

array4=array1[:3]
print(array4)

array5=array1[3:]
print(array5)

array6=array1[:]
print(array6)

[1 2 3 4 5 6 7 8 9]
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [28]:
#2차원 ndarray에서 슬라이싱으로 데이터에 접근하기
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array 2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array 2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('array 2d[1:3, :]\n', array2d[1:3, :])
print('array 2d[:, :]\n', array2d[:, :])
print('array 2d[:2, 1:]\n', array2d[:2, 1:])
print('array 2d[:2, 0]\n', array2d[:2, 0]) #****

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array 2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array 2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array 2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array 2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array 2d[:2, 1:]
 [[2 3]
 [5 6]]
array 2d[:2, 0]
 [1 4]


In [29]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


### 팬시 인덱싱
- 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환

In [30]:
#2차원 ndarray의 팬시 인덱싱
array1d=np.arange(start=1, stop=10)
array2d=array1d.reshape(3,3)

array3=array2d[[0,1],2]
print('array2d[[0,1],2] => ', array3.tolist())

array4=array2d[[0,1],0:2]
print('array2d[[0,1],0:2] => ', array4.tolist())

array5=array2d[[0,1]]
print('array2d[[0,1]] => ', array5.tolist())

array2d[[0,1],2] =>  [3, 6]
array2d[[0,1],0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


### 불린 인덱싱
- 조건 필터링과 검색을 동시에 할 수 있기 때문에 자주 사용되는 인덱싱 방식


In [32]:
array1d=np.arange(start=1, stop=10)
#[] 안에 array1d>5 Boolean indexing을 적용
array3=array1d[array1d>5]
print('array1d > 5 Boolean Indexing 결과 값: ', array3)

array1d > 5 Boolean Indexing 결과 값:  [6 7 8 9]


In [33]:
#넘파이 ndarray 객체에 조건식 할당하는 경우
array1d>5 #5보다 큰 경우는 True, 그렇지 않으면 False값 반환환

array([False, False, False, False, False,  True,  True,  True,  True])

In [34]:
#array[]내에 인덱스로 입력하면 동일한 데이터 세트가 반환됨
boolean_indexes=np.array([False, False, False, False, False,  True,  True,  True,  True])
array3=array1d[boolean_indexes]     #array1d[array1d>5]와 같은 결과
print('불린 인덱스로 필터링 결과:',array3) 

불린 인덱스로 필터링 결과: [6 7 8 9]


## 행렬의 정렬 - sort()와 argsort()

###행렬 정렬
- np.sort(): 원행렬은 그대로 유지한 채 원형렬의 정렬된 행렬 반환
- ndarray.sort(): 원행렬 자체를 정렬한 형태로 변환, 값은 None

In [36]:
org_array=np.array([3,1,9,5])
print('원본 행렬:', org_array)

#np.sort()로 정렬: 원본 행렬 변경x
sort_array1=np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 정렬 행렬:', org_array)

#ndarray.sort()로 정렬: 원본 행렬 자체를 정렬한 값으로 변환환
sort_array2=org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 정렬 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [37]:
#내림차순 정렬 시 [::-1] 적용
sort_array1_desc=np.sort(org_array)[::-1]
print('내림차순으로 정렬:',sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [39]:
#행렬이 2차원 이상일 경우 axis축 값 설정을 통해 row, col 방향으로 정렬 수행 가능
array2d=np.array([[8,10],
                  [7,1]])

sort_array2d_axis0=np.sort(array2d, axis=0)
print('row 방향으로 정렬:\n',sort_array2d_axis0)

sort_array2d_axis1=np.sort(array2d, axis=1)
print('col 방향으로 정렬:\n',sort_array2d_axis1)

row 방향으로 정렬:
 [[ 7  1]
 [ 8 10]]
col 방향으로 정렬:
 [[ 8 10]
 [ 1  7]]


### 정렬된 행렬의 인덱스 반환하기
- np.argsort(): 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 변환함

In [40]:
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬시 원본 행렬의 인덱스: [1 0 3 2]


In [41]:
# 내림차순 정렬 시의 원본 행렬 인덱스 구하기: np.argsort()[::-1] 사용
org_array=np.array([3,1,9,5])
sort_indices_desc=np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [48]:
import numpy as np
name_array=np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array=np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


## 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

### 행렬 내적(행렬 곱)
- np.dot()이용

In [50]:
A=np.array([[1,2,3],
            [4,5,6]])
B=np.array([[7,8],
            [9,10],
            [11,12]])
dot_product=np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


## 전치 행렬
- 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬
- transpose() 이용

In [51]:
A=np.array([[1,2],
            [3,4]])
transpose_mat=np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
