<a href="https://colab.research.google.com/github/snghynn/ESAA-YB/blob/main/ESSA_0313_Numpy_HW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
np.show_config()

1.22.4
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
z=np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
z=np.zeros((10,0))
print('%d bytes' % (z.size*z.itemsize))

0 bytes


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
z=np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
z=np.arange(10)
z=z[::-1]
print(z)

[9 8 7 6 5 4 3 2 1 0]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
z=np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
z=np.nonzero([1,2,0,0,4,0])
print(z)

(array([0, 1, 4]),)


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [ ]:
z=np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [ ]:
z=np.random.random((3,3,3))
print(z)

[[[0.58812234 0.29225856 0.70616646]
  [0.87668526 0.11841993 0.11575044]
  [0.13357121 0.95463854 0.10543554]]

 [[0.66518449 0.97522727 0.79425565]
  [0.3074296  0.20073801 0.57080814]
  [0.62844732 0.43605172 0.95371215]]

 [[0.70997346 0.18326417 0.04617993]
  [0.37820459 0.53284484 0.45718079]
  [0.09324339 0.1565126  0.32218381]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [ ]:
np.random.random((10))

array([0.88774783, 0.83118993, 0.97045108, 0.3369313 , 0.44442571,
       0.32228639, 0.49705155, 0.69695979, 0.68068059, 0.76083292])

In [ ]:
z=np.random.random((10,10))
min_z, max_z=z.min(), z.max()
print(min_z, max_z)

0.009993106685157516 0.9635553013595772


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [ ]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5203571313998938


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [ ]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
print(np.unravel_index(99, (6,7,8)))

(1, 5, 3)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-0.20578526 -0.44792861  1.57766588  0.44322345  0.41252313]
 [ 1.21598366  0.4514297   1.65412283  1.19470961 -1.16785351]
 [-0.41341187 -1.62531336  0.44667768 -0.72620887 -1.51746243]
 [-1.24595038 -0.37514893 -0.83958844  1.10880912 -1.16234488]
 [-0.67400674  1.44206925  0.17122116  0.93747668 -0.65490888]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
color=np.dtype([("r", np.ubyte),
                ("g", np.ubyte),
                ("b", np.ubyte),
                ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
print(np.ones((5,3)) @np.ones((3,2)))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
z=np.arange(11)
z[(3<z)&(z<8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1)) #sum에서 -1은 시작값을 의미
from numpy import *
print(sum(range(5),-1)) #np.sum에서 -1은 축 지정을 의미

9
10


In [ ]:
?sum

In [ ]:
?np.sum

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.arange(11)

In [ ]:
Z**Z

array([          1,           1,           4,          27,         256,
              3125,       46656,      823543,    16777216,   387420489,
       10000000000])

In [ ]:
2<<Z>>2

array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256, 512])

In [ ]:
3<<Z>>3

array([  0,   0,   1,   3,   6,  12,  24,  48,  96, 192, 384])

In [ ]:
1<<Z>>1

array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256, 512])

In [ ]:
Z<-Z

array([False, False, False, False, False, False, False, False, False,
       False, False])

In [ ]:
1j*Z

array([0. +0.j, 0. +1.j, 0. +2.j, 0. +3.j, 0. +4.j, 0. +5.j, 0. +6.j,
       0. +7.j, 0. +8.j, 0. +9.j, 0.+10.j])

In [ ]:
print(Z/1/1)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
print(Z<Z>Z)

ValueError: ignored

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-48-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-48-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [5]:
import numpy as np
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1, Z2))

[0 3 5 7]


In [6]:
np.random.randint(0,10,10)

array([5, 9, 6, 1, 8, 2, 4, 5, 4, 7])

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [7]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-7-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [ ]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [8]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [9]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.negative(A,out=A)
np.divide(A,2,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [10]:
Z = np.random.uniform(0,10,10)
print(Z)

print(Z - Z%1)
print(np.floor(Z))
print(np.ceil(Z) - 1)
print(np.trunc(Z))

[9.45108995 6.35349158 8.93341706 6.69934708 4.20512621 6.46151254
 7.29386152 6.98411724 2.83153903 2.21179216]
[9. 6. 8. 6. 4. 6. 7. 6. 2. 2.]
[9. 6. 8. 6. 4. 6. 7. 6. 2. 2.]
[9. 6. 8. 6. 4. 6. 7. 6. 2. 2.]
[9. 6. 8. 6. 4. 6. 7. 6. 2. 2.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [11]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [12]:
np.linspace(0,1,11) #벡터 생성
np.linspace(0,1,11, endpoint=False)
np.linspace(0,1,11, endpoint=False)[1:] #0 제외하기

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [13]:
A = np.random.randint(0,2,5) #random 배열 만들기
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal) 

False


In [14]:
equal = np.array_equal(A,B)
print(equal)

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [15]:
#cartesian coordinates: 직교 좌표계
#polar coordinates: 극좌표계_ 평면 위의 위치를 각도와 거리를 써서 나타내는 2차원 좌표계
Z = np.random.random((10,2))
print(Z)
X, Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[[0.21249096 0.91282439]
 [0.51504953 0.88529703]
 [0.81960228 0.81854477]
 [0.42271038 0.65310717]
 [0.46161379 0.34112533]
 [0.55108709 0.67141646]
 [0.09297425 0.74582539]
 [0.22830443 0.42684131]
 [0.10199309 0.57446581]
 [0.3769245  0.53633532]]
[0.93723037 1.02422012 1.15834513 0.77796725 0.57398064 0.86861789
 0.75159812 0.48406241 0.5834497  0.65553616]
[1.34208538 1.04388042 0.78475261 0.99637104 0.63641369 0.88351078
 1.44677656 1.07964372 1.39508311 0.95820857]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [21]:
Z = np.random.random(10)  #벡터 생성
print(Z)
Z.argmax() #힌트대로 maximum value index를 볼까?

[0.6362605  0.96152073 0.57769493 0.33818262 0.46758206 0.60410438
 0.74793891 0.045655   0.3840188  0.67074286]


1

In [22]:
Z[Z.argmax()] = 0   #0으로 채우기
print(Z)

[0.6362605  0.         0.57769493 0.33818262 0.46758206 0.60410438
 0.74793891 0.045655   0.3840188  0.67074286]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [23]:
Z = np.arange(100)
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [24]:
v = np.random.uniform(0, 100)
print(v)

75.50226702352995


In [25]:
index = (np.abs(Z-v)).argmin()  #computing the distance btw Z & v
print(index)  #printing the index of min value

76


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [26]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [27]:
for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [28]:
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [29]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [30]:
np.random.choice(range(n*n), p)

array([79, 66, 87])

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [35]:
Z = np.random.randint(0,10,(3,3))
print(Z)

[[2 4 6]
 [9 5 3]
 [5 7 1]]


In [36]:
# column 1
print(Z[Z[:,0].argsort()])

[[2 4 6]
 [5 7 1]
 [9 5 3]]


In [37]:
# column 2
print(Z[Z[:,1].argsort()])

[[2 4 6]
 [9 5 3]
 [5 7 1]]


In [38]:
# column 3
print(Z[Z[:,2].argsort()])

[[5 7 1]
 [9 5 3]
 [2 4 6]]
